version: '3.7'

services:
  react-portfolio:
    environment:
      VIRTUAL_HOST: euge.dev, www.euge.dev
      LETSENCRYPT_HOST: euge.dev, www.euge.dev
      LETSENCRYPT_EMAIL: eugeniasalazar745@gmail.com
      VIRTUAL_PORT: 3500
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 3500
    ports:
      - 3500:3500
      # - 80:3500
    container_name: react-portfolio
    volumes:
      - .:/usr/src/app
      - ./build:/usr/src/app/build
      - /usr/src/app/node_modules

networks:
  default:
    external:
      name: nginx-proxy