version: '3.7'

services:
  react-portfolio:
    environment:
      VIRTUAL_HOST: euge.dev, www.euge.dev
      LETSENCRYPT_HOST: euge.dev, www.euge.dev
      LETSENCRYPT_EMAIL: eugeniasalazar745@gmail.com
      VIRTUAL_PORT: 3000
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 3000
    ports:
      - 3000:3000
    container_name: react-portfolio
    volumes:
      - .:/usr/src/app
      - ./build:/usr/src/app/build
      - /usr/src/app/node_modules

# networks:
#   default:
#     external:
#       name: nginx-proxy